apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.lnd.name }}
spec:
  containers:
  - name: {{ .Values.lnd.name }}
    image: "{{ .Values.lnd.image.repository }}:{{ .Values.lnd.image.tag | default .Chart.AppVersion }}"
    imagePullPolicy: {{ .Values.lnd.image.pullPolicy }}
    ports:
    - containerPort: {{ .Values.lnd.service.port }}
    env:
      - name: MY_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
    readinessProbe:
      exec:
        command: [ "sh", "-c", "nslookup {{ .Values.lnd.name }}.${MY_NAMESPACE}.svc.cluster.local" ]
      initialDelaySeconds: 5
      periodSeconds: 10
    volumeMounts:
    - name: {{ .Values.lnd.name }}
      mountPath: /root/.lnd/lnd.conf
      subPath: lnd.conf
    command: ["sh", "-c"]
    args:
      - >
        exec lnd
        --externalip={{ .Values.lnd.name }}.${MY_NAMESPACE}.svc.cluster.local
  volumes:
  - name: {{ .Values.lnd.name }}
    configMap:
      name: {{ .Values.lnd.name }}
