apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.lnd.name }}
spec:
  selector:
    app: {{ .Values.lnd.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.lnd.service.port }}
    targetPort: {{ .Values.lnd.service.port }}
  type: {{ .Values.lnd.service.type }}