lnd:
  name: "lnd"
  image:
    repository: "lightninglabs/lnd"
    tag: "v0.18.2-beta"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9735
  config:
    alias: "mynode"
    rpcuser: "user"
    rpcpassword: "password"
    bitcoindHost: "bitcoind"  # Replace with your Bitcoind pod's service name or IP
    bitcoindRpcPort: 18443
    bitcoindZmqPubRawBlock: "tcp://bitcoind:28332"
    bitcoindZmqPubRawTx: "tcp://bitcoind:28333"
    network: "signet"
