name: test

on:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  build:
    needs: [ruff]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          file: src/templates/rpc/Dockerfile_rpc
          context: .
          tags: local/warnet-rpc:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/warnet.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: warnet
          path: /tmp/warnet.tar
  test:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: [compose, k8s]
        test: [scenarios_test.py, rpc_test.py, graph_test.py, ln_test.py, get_service_ip_test.py]
    steps:
      - uses: actions/checkout@v4
      - if: matrix.backend == 'compose'
        uses: ./.github/actions/compose
      - if: matrix.backend == 'k8s'
        uses: ./.github/actions/k8s
      - if: matrix.backend == 'k8s'
        run: |
          kubectl port-forward svc/rpc 9276:9276 &
      - name: Run tests
        run: ./test/${{matrix.test}} ${{matrix.backend}}
  build-test:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/compose
      - run: ./test/build_branch_test.py compose
  deploy:
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_RPC_REPO }}
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            maintainer=bitcoindevproject
            org.opencontainers.image.title=warnet-rpc
            org.opencontainers.image.description=Warnet RPC server
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push production RPC image
        uses: docker/build-push-action@v5
        with:
          file: src/templates/rpc/Dockerfile_rpc
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push dev RPC image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          file: src/templates/rpc/Dockerfile_rpc_dev
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_RPC_REPO }}:dev
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
